---
# tasks file for nginx-server

- name : Debugging ONLY
  debug:
    msg: "This is from khangtictoc hahaha"

- command: whoami
  register: whoami
  
- debug:
    var: whoami.stdout
  



# - name: Install nginx
#   apt:
#     name: nginx
#     state: present

# - name: Start nginx
#   service:
#     name: nginx
#     state: started
