---

- name : Debugging ONLY
  debug:
    msg: "This is from khangtictoc hahaha"

- name: Get $USER used for executing role
  command: whoami
  register: whoami
  changed_when: False
  
- name: Print out $USER used for executing role
  debug:
    var: whoami.stdout

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Add default host configuration
  copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Reload nginx
