# ---
# - name: Converge
#   hosts: all
#   gather_facts: false
#   tasks:
#     - name: Replace this task with one that validates your content
#       ansible.builtin.debug:
#         msg: "This is the one effective test"
#     - name: Testing role
#       ansible.builtin.include_role:
#         name: nginx-server
#         tasks_from: main.yml

- name: Converge
  hosts: localhost
  gather_facts: false
  become: true
  roles:
    - role: Ansible_Molecule-Nginx-Test-By-Instance