---
driver:
  name: default
platforms:
  - name: instance
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
  ansible_args:
    - --ask-become-pass
# verifier:
#   name: testinfra
#   options:
#     # pytest-ansible conflicts with --connection
#     p: "no:pytest-ansible"

#     # avoid loading global pyproject.toml options, so we don't
#     # load the setting that says "disable testinfra"
#     c: "."

lint: |
  set -e
  yamllint . -c .yamllint
  ansible-lint -c .ansible-lint

role_name_check: 1