---
driver:
  name: default
  
    # ansible_connection_options:
    #   ansible_connection: local
platforms:
  - name: instance
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
  ansible_args:
    - --ask-become-pass

role_name_check: 1